/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertor;

/**
 *
 * @author DELL
 */
public class pages extends javax.swing.JFrame {

    /**
     * Creates new form pages
     */
    public pages() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B2D = new javax.swing.JButton();
        B2O = new javax.swing.JButton();
        B2H = new javax.swing.JButton();
        D2B = new javax.swing.JButton();
        D2O = new javax.swing.JButton();
        D2H = new javax.swing.JButton();
        O2B = new javax.swing.JButton();
        O2D = new javax.swing.JButton();
        O2H = new javax.swing.JButton();
        H2B = new javax.swing.JButton();
        H2D = new javax.swing.JButton();
        H2O = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Here is our convertor");

        B2D.setText("Binary to Decimal");
        B2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2DActionPerformed(evt);
            }
        });

        B2O.setText("Binary to Octal");
        B2O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2OActionPerformed(evt);
            }
        });

        B2H.setText("Binaray to HexaDecimal");
        B2H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2HActionPerformed(evt);
            }
        });

        D2B.setText("Decimal to Binary");
        D2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2BActionPerformed(evt);
            }
        });

        D2O.setText("Decimal to Octal");
        D2O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2OActionPerformed(evt);
            }
        });

        D2H.setText("Decimal to HexaDecimal");
        D2H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2HActionPerformed(evt);
            }
        });

        O2B.setText("Octal to Binary");
        O2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O2BActionPerformed(evt);
            }
        });

        O2D.setText("Octal to Decimal");
        O2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O2DActionPerformed(evt);
            }
        });

        O2H.setText("Octal to HexaDecimal");
        O2H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O2HActionPerformed(evt);
            }
        });

        H2B.setText("HexaDecimal to Binary");
        H2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2BActionPerformed(evt);
            }
        });

        H2D.setText("HexaDecimal to Decimal");
        H2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2DActionPerformed(evt);
            }
        });

        H2O.setText("HexaDecimal to Octal");
        H2O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2OActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(D2B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(O2B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(H2B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D2O, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(H2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B2O, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(O2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D2H, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B2H, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(O2H, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(H2O, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B2O)
                    .addComponent(B2H)
                    .addComponent(B2D))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D2O)
                    .addComponent(D2H)
                    .addComponent(D2B))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(O2B)
                    .addComponent(O2D)
                    .addComponent(O2H))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(H2B)
                    .addComponent(H2D)
                    .addComponent(H2O))
                .addGap(168, 168, 168))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B2OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2OActionPerformed
        // TODO add your handling code here:
        new B2O().setVisible(true);
        
    }//GEN-LAST:event_B2OActionPerformed

    private void O2HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O2HActionPerformed
        // TODO add your handling code here:
        new O2H().setVisible(true);
    }//GEN-LAST:event_O2HActionPerformed

    private void B2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2DActionPerformed
        // TODO add your handling code here:
        new B2D().setVisible(true);
        
    }//GEN-LAST:event_B2DActionPerformed

    private void B2HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2HActionPerformed
        // TODO add your handling code here:
         new B2H().setVisible(true);
    }//GEN-LAST:event_B2HActionPerformed

    private void O2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O2BActionPerformed
        // TODO add your handling code here:
        new O2B().setVisible(true);
    }//GEN-LAST:event_O2BActionPerformed

    private void O2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O2DActionPerformed
        // TODO add your handling code here:
        new O2D().setVisible(true);
    }//GEN-LAST:event_O2DActionPerformed

    private void D2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2BActionPerformed
        // TODO add your handling code here:
        new D2B().setVisible(true);
    }//GEN-LAST:event_D2BActionPerformed

    private void D2OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2OActionPerformed
        // TODO add your handling code here:
        new D2O().setVisible(true);
    }//GEN-LAST:event_D2OActionPerformed

    private void D2HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2HActionPerformed
        // TODO add your handling code here:
        new D2H().setVisible(true);
    }//GEN-LAST:event_D2HActionPerformed

    private void H2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2BActionPerformed
        // TODO add your handling code here:
        new H2B().setVisible(true);
    }//GEN-LAST:event_H2BActionPerformed

    private void H2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2DActionPerformed
        // TODO add your handling code here:
        new H2D().setVisible(true);
    }//GEN-LAST:event_H2DActionPerformed

    private void H2OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2OActionPerformed
        // TODO add your handling code here:
        new H2O().setVisible(true);
    }//GEN-LAST:event_H2OActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B2D;
    private javax.swing.JButton B2H;
    private javax.swing.JButton B2O;
    private javax.swing.JButton D2B;
    private javax.swing.JButton D2H;
    private javax.swing.JButton D2O;
    private javax.swing.JButton H2B;
    private javax.swing.JButton H2D;
    private javax.swing.JButton H2O;
    private javax.swing.JButton O2B;
    private javax.swing.JButton O2D;
    private javax.swing.JButton O2H;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
